/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillBillIdRouteImport } from './routes/bill.$billId'

const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillBillIdRoute = BillBillIdRouteImport.update({
  id: '/bill/$billId',
  path: '/bill/$billId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/tenant': typeof TenantRoute
  '/bill/$billId': typeof BillBillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/tenant': typeof TenantRoute
  '/bill/$billId': typeof BillBillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/tenant': typeof TenantRoute
  '/bill/$billId': typeof BillBillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/owner' | '/setup' | '/tenant' | '/bill/$billId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/owner' | '/setup' | '/tenant' | '/bill/$billId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/owner'
    | '/setup'
    | '/tenant'
    | '/bill/$billId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRoute
  SetupRoute: typeof SetupRoute
  TenantRoute: typeof TenantRoute
  BillBillIdRoute: typeof BillBillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill/$billId': {
      id: '/bill/$billId'
      path: '/bill/$billId'
      fullPath: '/bill/$billId'
      preLoaderRoute: typeof BillBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRoute,
  SetupRoute: SetupRoute,
  TenantRoute: TenantRoute,
  BillBillIdRoute: BillBillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
